daas:  
  build: .
  ports: 
    - 9091:9091
  volumes:
    - /go/src/github.com/AuthenticFF/DaaS/
  links:
    - database
  environment:
    - DB_NAME=daas
    - PORT=9091

database:  
  image: mongo:3.0.7
  command: mongod --smallfiles --quiet --logpath=/dev/null